spring:
  application:
    name: coordinator
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:coordinator;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:h2:mem:coordinator;DB_CLOSE_DELAY=-1;MODE=MySQL
    user: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    view:
      prefix: /static/
      suffix: .html
cache:
  key:
    lowest-prices-by-category: lowest-prices-by-category
    lowest-prices-by-brand: lowest-prices-by-brand
    min-max-prices-by-category: min-max-prices-by-category
